-- Employee 4: Store Engagement + Security
create table if not exists company_sms_logs (id uuid primary key, company_id text not null, recipient text not null, sender text, message text not null, status text not null check (status in ('PENDING','SENT','DELIVERED','FAILED','REJECTED','UNKNOWN')), provider text, provider_reference text, cost numeric, currency text, related_entity_type text, related_entity_id text, error_message text, created_at timestamptz not null default now(), sent_at timestamptz, failed_at timestamptz);
create index if not exists idx_company_sms_logs_company_created on company_sms_logs(company_id,created_at desc);
create table if not exists company_sms_automations (id uuid primary key, company_id text not null, trigger text not null check (trigger in ('ORDER_CONFIRMATION','ORDER_SHIPPED','OUT_FOR_DELIVERY','DELIVERED','NEW_ORDER_TO_MANAGER','POS_PURCHASE_CONFIRMATION')), is_enabled boolean not null default true, message_template text not null, sender text, recipient text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists uq_company_sms_automation_trigger on company_sms_automations(company_id,trigger);
create table if not exists company_announcements (id uuid primary key, company_id text not null, title text not null, text text not null, link text, text_color text, background_color text, alignment text check (alignment in ('LEFT','CENTER','RIGHT')), is_active boolean not null default true, priority integer not null default 0, placement text not null check (placement in ('ALL_PAGES','HOMEPAGE','SELECTED_PAGES')), selected_pages jsonb not null default '[]'::jsonb, start_date timestamptz, end_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists company_splash_ads (id uuid primary key, company_id text not null, title text not null, desktop_image_id text, mobile_image_id text, link text, is_active boolean not null default true, start_date timestamptz, end_date timestamptz, close_delay_seconds integer not null default 0 check (close_delay_seconds>=0), display_duration_seconds integer not null default 0 check (display_duration_seconds>=0), frequency text not null default 'ONCE_PER_SESSION' check (frequency in ('EVERY_VISIT','ONCE_PER_SESSION','ONCE_PER_DAY')), excluded_pages jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists company_splash_ad_events (id uuid primary key, company_id text not null, splash_ad_id uuid not null, event_type text not null check (event_type in ('VIEW','CLICK')), created_at timestamptz not null default now());
create index if not exists idx_splash_events_company_ad on company_splash_ad_events(company_id,splash_ad_id,created_at desc);
create table if not exists company_store_policies (id uuid primary key, company_id text not null, type text not null check (type in ('SHIPPING','RETURNS','REFUND','EXCHANGE','CANCELLATION','PRIVACY','TERMS','WARRANTY','CUSTOM')), title_ar text, title_en text, content_ar text, content_en text, is_active boolean not null default true, display_order integer not null default 0, placements jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists company_legal_information (id text primary key, company_id text not null unique, registration_number text, authority_name text, authority_logo_media_id text, business_information jsonb not null default '{}'::jsonb, placements jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists company_login_history (id uuid primary key, company_id text not null, user_id text, email text, status text not null check(status in ('SUCCESS','FAILURE')), ip_address text, user_agent text, authentication_method text, failure_reason text, created_at timestamptz not null default now());
create index if not exists idx_login_history_company_created on company_login_history(company_id,created_at desc);
create table if not exists company_login_security (id text primary key, company_id text not null, email text not null, failed_attempts integer not null default 0, last_failed_at timestamptz, locked_until timestamptz, unique(company_id,email));
create table if not exists company_ip_blocks (id uuid primary key, company_id text not null, ip_address text not null, block_type text not null check(block_type in ('MANUAL','AUTOMATIC_TEMPORARY')), reason text, is_active boolean not null default true, created_at timestamptz not null default now(), expires_at timestamptz, unblocked_at timestamptz, unblocked_by text);
create index if not exists idx_ip_blocks_lookup on company_ip_blocks(company_id,ip_address,is_active);
