import React from "react";
import AdminLayout from "../components/AdminLayout.jsx";
import { apiRequest } from "../utils/api.js";
import { hasPermission } from "../data/permissions.js";
import { POLICY_TYPE_LABELS, POLICY_PLACEMENT_LABELS, makeLabeler, joinLabels } from "../utils/employee4Labels.js";
import { useClientPager, ClientPagerControls } from "../components/Employee4Workspace.jsx";

const types = ["SHIPPING", "RETURNS", "REFUNDS", "EXCHANGE", "CANCELLATION", "PRIVACY", "TERMS", "WARRANTY", "CUSTOM"];
const placementOptions = ["FOOTER", "CART", "CHECKOUT", "STANDALONE_PAGE"];
const empty = { type: "SHIPPING", title_ar: "", title_en: "", content_ar: "", content_en: "", is_active: true, display_order: 0, placements: ["FOOTER"] };

export default function AdminPoliciesPage({ company, currentUser, language = "en", modules, onNavigate, onLogout, onLanguageChange, onReturnToPlatform, onSwitchCompany, onToggleDarkMode, isDarkMode }) {
  const ar = language === "ar";
  const L = makeLabeler(ar);
  const canManage = hasPermission(currentUser, "policies.manage"); const [items, setItems] = React.useState([]); const [editing, setEditing] = React.useState(null); const [error, setError] = React.useState(""); const [notice, setNotice] = React.useState("");
  const pager = useClientPager([...items].sort((a, b) => Number(a.display_order) - Number(b.display_order)), 10);
  const layout = { activePage: "admin-policies", company, currentUser, isDarkMode, language, modules, onLanguageChange, onLogout, onNavigate, onReturnToPlatform, onSwitchCompany, onToggleDarkMode };
  const load = React.useCallback(async () => { try { setItems((await apiRequest("/admin/policies")).items || []); } catch (e) { setError(e.message); } }, []); React.useEffect(() => { void load(); }, [load]);
  async function save(e) { e.preventDefault(); try { const data = editing.id ? await apiRequest(`/admin/policies/${editing.id}`, { method: "PATCH", body: JSON.stringify(editing) }) : await apiRequest("/admin/policies", { method: "POST", body: JSON.stringify(editing) }); setItems((cur) => editing.id ? cur.map((x) => x.id === data.id ? data : x) : [...cur, data].sort((a,b) => Number(a.display_order)-Number(b.display_order))); setEditing(null); setNotice(ar ? "تم حفظ السياسة." : "Policy saved."); } catch (e2) { setError(e2.message); } }
  async function remove(id) { if (!window.confirm(ar ? "حذف هذه السياسة؟" : "Delete policy?")) return; try { await apiRequest(`/admin/policies/${id}`, { method: "DELETE" }); setItems((cur) => cur.filter((x) => x.id !== id)); } catch (e) { setError(e.message); } }
  function togglePlacement(value) { setEditing((cur) => ({ ...cur, placements: cur.placements.includes(value) ? cur.placements.filter((x) => x !== value) : [...cur.placements, value] })); }
  return <AdminLayout {...layout} title={ar ? "سياسات المتجر" : "Store Policies"} subtitle={ar ? "إدارة السياسات متعددة اللغات ومواقع ظهورها." : "Manage multilingual policies, ordering, activation and placement."}>
    {notice && <div className="message-panel success">{notice}</div>}{error && <div className="message-panel error">{error}</div>}
    <section className="admin-panel-card"><div className="admin-section-head"><div><h2>{ar ? "السياسات" : "Policies"}</h2><p>{ar ? "تقرأ الواجهة الأمامية السياسات النشطة ديناميكياً." : "Storefront reads active policies dynamically."}</p></div>{canManage && <button className="admin-primary-button" onClick={() => setEditing({ ...empty, placements: [...empty.placements] })} type="button">{ar ? "إضافة سياسة" : "Add policy"}</button>}</div><div className="admin-data-table-wrap"><table className="admin-data-table"><thead><tr><th>{ar ? "الترتيب" : "Order"}</th><th>{ar ? "النوع" : "Type"}</th><th>{ar ? "العناوين" : "Titles"}</th><th>{ar ? "نشطة" : "Active"}</th><th>{ar ? "الموضع" : "Placement"}</th><th className="admin-data-table-actions">{ar ? "إجراء" : "Actions"}</th></tr></thead><tbody>{pager.pageItems.map((x) => <tr key={x.id}><td>{x.display_order}</td><td>{L(POLICY_TYPE_LABELS, x.type)}</td><td>{x.title_en || x.title_ar}<span className="table-muted">{x.title_ar || "—"}</span></td><td>{x.is_active === false ? (ar ? "معطّلة" : "Disabled") : (ar ? "مفعّلة" : "Enabled")}</td><td>{joinLabels(POLICY_PLACEMENT_LABELS, x.placements, ar)}</td><td className="admin-data-table-actions" data-label={ar ? "الإجراء" : "Actions"}>{canManage ? <div className="row-actions"><button className="text-action" onClick={() => setEditing({ ...x, placements: x.placements || [] })}>{ar ? "تعديل" : "Edit"}</button><button className="text-action danger" onClick={() => void remove(x.id)}>{ar ? "حذف" : "Delete"}</button></div> : "—"}</td></tr>)}</tbody></table></div><ClientPagerControls {...pager} ar={ar} /></section>
    {editing && canManage &&<section className="admin-panel-card"><form onSubmit={save} className="admin-form-grid"><label>{ar ? "النوع" : "Type"}<select value={editing.type} onChange={(e) => setEditing({ ...editing, type: e.target.value })}>{types.map((x) => <option key={x} value={x}>{L(POLICY_TYPE_LABELS, x)}</option>)}</select></label><label>{ar ? "ترتيب العرض" : "Display order"}<input type="number" value={editing.display_order} onChange={(e) => setEditing({ ...editing, display_order: Number(e.target.value) })} /></label><label>{ar ? "العنوان (إنجليزي)" : "Title EN"}<input value={editing.title_en || ""} onChange={(e) => setEditing({ ...editing, title_en: e.target.value })} /></label><label>{ar ? "العنوان (عربي)" : "Title AR"}<input dir="rtl" value={editing.title_ar || ""} onChange={(e) => setEditing({ ...editing, title_ar: e.target.value })} /></label><label className="full-field">{ar ? "المحتوى (إنجليزي)" : "Content EN"}<textarea rows="7" value={editing.content_en || ""} onChange={(e) => setEditing({ ...editing, content_en: e.target.value })} /></label><label className="full-field"><span dir="rtl">{ar ? "المحتوى (عربي)" : "Content AR"}</span><textarea dir="rtl" rows="7" value={editing.content_ar || ""} onChange={(e) => setEditing({ ...editing, content_ar: e.target.value })} /></label><fieldset className="full-field"><legend>{ar ? "الموضع" : "Placement"}</legend>{placementOptions.map((x) => <label className="checkbox-line" key={x}><input type="checkbox" checked={(editing.placements || []).includes(x)} onChange={() => togglePlacement(x)} />{L(POLICY_PLACEMENT_LABELS, x)}</label>)}</fieldset><label className="checkbox-line"><input type="checkbox" checked={editing.is_active !== false} onChange={(e) => setEditing({ ...editing, is_active: e.target.checked })} /> {ar ? "نشطة" : "Active"}</label><div className="row-actions"><button className="admin-primary-button" type="submit">{ar ? "حفظ" : "Save"}</button><button className="text-action" type="button" onClick={() => setEditing(null)}>{ar ? "إلغاء" : "Cancel"}</button></div></form></section>}
  </AdminLayout>;
}
